layout_spectrum: 0.9433
typography_spectrum: 0.5865521
color:
  saturation: 0.9403539
  lightness: 0.7039022
  brandStrength: 0.07152952
  rhythmicContrast: 0.9647961
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
name: MyDailyPhoto
